stages:
  - test
  - deploy_dev
  - release

test:
  stage: test
  tags:
    - docker
  image: docker-registry.linagora.com:5000/public-releases/openpaas-esn-test-helper:1.0.0
  services:
    - mongo:3.4
    - elasticsearch:2.4
    - redis:3
    - rabbitmq:3.6
  script:
    - npm i
    - bower i --allow-root
    - grunt --chunk=1 --ci
  except:
    variables:
      - $SKIP_TESTS
    refs:
      - tags@linagora/lgs/openpaas/linagora.esn.linshare

.deploy_dev:
  stage: deploy_dev
  tags:
    - dev.open-paas.org
    - deployment
  environment:
    name: dev
    url: https://dev.open-paas.org
  only:
    - master@linagora/lgs/openpaas/linagora.esn.linshare
  script:
    - cd /srv/${CI_PROJECT_NAME}
    - git fetch --all
    - git checkout ${CI_COMMIT_SHA}
    - npm install --production
    - npm update --production
    - npm prune
    - bower install --production
    - bower prune
    - git checkout -- .
    - sudo /etc/init.d/rse.dev restart

npm-release:
  stage: release
  image: node:8
  tags:
    - docker
  only:
    - tags@linagora/lgs/openpaas/linagora.esn.linshare
  except:
    variables:
      - $SKIP_RELEASE
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
    - npm i --production
    - npm i -g bower
    - bower i --allow-root --production
    - npm publish